# Header
menu:
  Home: /
  About: About/
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-57072621-1
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
