# Header
menu:
  Home: /
  About: About/
  Archives: /archives
rss: /atom.xml

# Content
subtitle: A Hungry Fool
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
  - category
  - tagcloud
  - archive
  - recent_posts
  - follow

# Miscellaneous
favicon: /favicon.png
twitter: "Oldgunix"
google_plus:
fb_admins:
fb_app_id:
